# Generated by Django 4.2 on 2023-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('area_code', models.IntegerField()),
                ('time_slots', models.CharField(max_length=80)),
            ],
        ),
    ]
