# Generated by Django 4.2 on 2023-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadshedding_calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapeTownSlots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('stage1', models.SmallIntegerField()),
                ('stage2', models.SmallIntegerField()),
                ('stage3', models.SmallIntegerField()),
                ('stage4', models.SmallIntegerField()),
                ('stage5', models.SmallIntegerField()),
                ('stage6', models.SmallIntegerField()),
                ('stage7', models.SmallIntegerField()),
                ('stage8', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'cape_town_slots',
                'managed': False,
            },
        ),
    ]
