# Generated by Django 4.2 on 2023-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadshedding_calc', '0002_capetownslots_capetownareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapeTownAreas',
            fields=[
                ('ct_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=80)),
                ('area_code', models.SmallIntegerField()),
            ],
        ),
    ]
