# Generated by Django 4.2 on 2023-06-14 08:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loadshedding_calc', '0003_capetownareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hour_cost', models.FloatField(null=True)),
                ('user_time_start', models.TimeField(default=datetime.time(0, 0))),
                ('user_time_end', models.TimeField(default=datetime.time(23, 59))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loadshedding_calc.capetownareas')),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
