# Generated by Django 4.2 on 2023-06-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadshedding_calc', '0004_profile_delete_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='loadshedding_calc.capetownareas'),
        ),
    ]
