# Generated by Django 4.2 on 2023-06-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadshedding_calc', '0005_alter_profile_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_hour_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
