# Generated by Django 4.2 on 2023-09-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadshedding_calc', '0006_alter_profile_user_hour_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapeTownPastStages',
            fields=[
                ('past_stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('stage', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'cape_town_past_stages',
                'managed': False,
            },
        ),
    ]
