# Generated by Django 4.2 on 2023-11-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadshedding_calc', '0007_capetownpaststages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapeTownPastSlots',
            fields=[
                ('past_slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('area_code', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
